# Generated by Django 5.2.11 on 2026-02-23 08:29

import django.db.models.deletion
import myapp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to=myapp.models.get_file_storage_path)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('file_size_bytes', models.BigIntegerField()),
                ('display_name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('category', models.CharField(default='General', max_length=100)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
